Repository hyeonahc/fast-bank-FE, pull requests merged in 2022-08, with the labels that each got.

#7 conf: Create dummy server
  dummyServer/db.json
  dummyServer/index.js
  dummyServer/jsconfig.json
  dummyServer/package.json
  dummyServer/routes.json
  dummyServer/yarn.lock
  package.json
Labels: conf

#8 #6 conf: Update dummy server
  dummyServer/db.json
  dummyServer/index.js
Labels: conf

#32 #30 feat: ProductModal sample layout Display
  src/components/ProductCard/data.js
  src/components/ProductCard/index.jsx
  src/components/ProductCard/style.js
  src/components/ProductDetailModal/index.jsx
  src/index.css
  src/pages/AllProductsPage/index.jsx
  src/styles/globalStyle.js
Labels: feat, design

#34 31 feat:Click to synchronize ProductCardComponents and ModalComponent
  src/components/ProductCard/index.jsx
Labels: feat
